name: regular actions get candidates

on:
  schedule:
    - cron: '0 6 * * *'  # 毎日15:00(6:00(UTC))に実行
  workflow_dispatch:       # 手動実行を可能にする設定


jobs:
  get_candidates:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Set PYTHONPATH
        run: |
          echo "PYTHONPATH=${env:PYTHONPATH};${env:GITHUB_WORKSPACE}" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8

      - name: initialize html/candidates
        run: |
          mkdir -p data/html/candidates/cs

      - name: Cache data files
        uses: actions/cache@v3
        with:
          path: data/candidates/
          key: ${{ runner.os }}-candidates-${{ github.run_number }}
          restore-keys: |
            ${{ runner.os }}-candidates-

      - name: Run script
        run: |
          python modules/regular_actions/get_candidates.py

      - name: cleanup
        if: always()
        run: |
          Remove-Item -Recurse -Force data/html/candidates/cs
