name: regular actions get candidates

on:
  schedule:
    - cron: '0 6 * * *'  # 毎日15:00(6:00(UTC))に実行
  workflow_dispatch:       # 手動実行を可能にする設定


jobs:
  get_candidates:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$PYTHONPATH:$GITHUB_WORKSPACE" >> $GITHUB_ENV
        
      - name: Run script
        run: |
          python regular_actions/get_candidates.py
