name: regular actions predict candidates

on:
  schedule:
    - cron: '30 6 * * *'  # 毎日15:30(6:30(UTC))に実行
  workflow_dispatch:       # 手動実行を可能にする設定


jobs:
  predict_candidates:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Set PYTHONPATH
        run: |
          echo "PYTHONPATH=${env:PYTHONPATH};${env:GITHUB_WORKSPACE}" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8

      - name: Cache data files
        uses: actions/cache@v3
        with:
          path: data/candidates/
          key: ${{ runner.os }}-candidates-${{ github.run_number }}
          restore-keys: |
            ${{ runner.os }}-candidates-

      - name: Run script
        run: |
          python modules/regular_actions/predict_candidates.py

      - name: save pred_df for artifact
        uses: actions/upload-artifact@v3
        with:
          name: pred_df-candidates
          path: |
            pred_candidates_full_*.csv
            pred_candidates_*.csv


  # アーティファクトをダウンロードして解凍する別のジョブ
  download_and_extract:
    runs-on: windows-latest
    needs: predict_candidates  # 予測ジョブの完了を待つ
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: pred_df-candidates
          path: .  # カレントディレクトリにダウンロード

      - name: Extract artifact
        run: |
          Expand-Archive -Path pred_df-candidates.zip -DestinationPath . -Force

