name: yearly actions

on:
  schedule:
    - cron: '0 0 8 1 *'  # 毎年1月8日午前0時 UTC
  workflow_dispatch:       # 手動実行を可能にする設定


jobs:
  yearly_scraping:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$PYTHONPATH:$GITHUB_WORKSPACE" >> $GITHUB_ENV
        
      - name: Run script
        run: |
          python regular_actions/yearly_scraping.py
